### ISSUE TITLE
Consulta SQL para obtener la variación de precio

### ISSUE THREAD

**Issue by darwinsalinas** [opobla/nicaventas#2]
Hola, buen día!
Tengo una duda en el caso de la consulta para obtener la variación de precio:
```SQL
SELECT MAX(variation) 
  FROM rules 
  WHERE
    city = "Leon" AND
    country = "ni" AND
    min_condition >= weather_id AND
    max_condition <= weather_id AND
    SKU = "AZ0001"
```
En esta consulta en realidad únicamente obtendría los resultados en los que la condición mínima y máxima sea igual a lo retornado por el API OpenWeatherMaps dado que estamos comparando que los valores que tenemos en base de datos para _**min_condition**_ y **_max_contidion_** sean mayores y menores respectivamente, por lo cual solo nos va a retornar los resultados en los que la condición mínima y máxima sean iguales a lo retornado por el API

Propuesta de cambio en la consulta:
En este caso se obtendría los resultados en los que el valor devuelto por el API de OpenWeatherMaps esté entre la condición mínima y la condición máxima:

```SQL
SELECT MAX(variation) 
  FROM rules 
  WHERE
    city = 'Leon' AND
    country = 'ni' AND
    weather_id >= min_condition AND
    weather_id <= max_condition AND
    sku = 'AZ00001'
```

**Comment by opobla** [comment]
Tiene sentido sí. La consulta SQL la hice de memoria, así es que es muy probable que me equivocara.

**Comment by darwinsalinas** [comment]
Ok, en mi caso realizaré la consulta de la manera en la que le he propuesto en el issue.
